#!/usr/bin/env bash

set -eu

here=$(cd "$(dirname "$0")" && pwd)
top_dir=$(cd "${here}"/.. && pwd)

scratch_dir="/tmp/servicelib-scratch"
mkdir -p $scratch_dir

env \
  PATH="${top_dir}/.tox/py37/bin:$PATH" \
  PYTHONPATH="${top_dir}/src:${top_dir}/samples" \
  SERVICELIB_CONFIG_URL="file://${here}/servicelib.yaml" \
  servicelib-client "$@"
